AWSTemplateFormatVersion: "2010-09-09"
Description: Main stactk
Parameters:
  OwnerNamen:
    Type: String
    Default: hboiton
    Description: name 

  ProyectName:
    Type: String
    Default: hboiton-stack
    Description: name proyect stack

  Environment:
    Type: String
    Default: dev-hboiton
    Description: Environment name to append to resources names and tags
 
  BucketURL:
    Type: String
    Default: https://hboiton-trambo.s3.amazonaws.com/templas_stack
    Description: link you my bucket

  DBName:
    Type: String
    Default: mywordpress
    Description: Name of Mysql database
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  
  DBUser:
    Type: String
    Default: mysqladmin
    Description: Name of Mysql admin user
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'

  DBPassword:
    Type: String
    Default :  wptrambo123
    Description: password of mysql admin
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
  
  CidrBlock:
    Type: String
    Default: 198.162.0.0/16
    Description: Please enter the IP range (CIDR notation) for this VPC

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${BucketURL}/vpc/vpc.yml
      TimeoutInMinutes: '60'
      Parameters:
        OwnerNamen: !Ref OwnerNamen
        ProyectName: !Ref ProyectName
        Environment: !Ref Environment
        CidrBlock: !Ref CidrBlock

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${BucketURL}/rds/rds.yml
      TimeoutInMinutes: '60'
      Parameters:
        OwnerNamen: !Ref OwnerNamen
        ProyectName: !Ref ProyectName
        Environment: !Ref Environment
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        VpcId: !GetAtt Vpc.Outputs.VPCID
        PrivateSubnet1: !GetAtt Vpc.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt Vpc.Outputs.PrivateSubnet2
  
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${BucketURL}/ec2/ec2.yml
      TimeoutInMinutes: '60'
      Parameters:
        OwnerNamen: !Ref OwnerNamen
        ProyectName: !Ref ProyectName
        Environment: !Ref Environment
        DBName: !Ref DBName 
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        DBAddress: !GetAtt RDS.Outputs.Endpoint
        VpcId: !GetAtt Vpc.Outputs.VPCID
        SubnetID: !GetAtt Vpc.Outputs.PublicSubnet1
        SecurityGroupServer: !GetAtt RDS.Outputs.EC2SecurityGroup
  
  DNS:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub ${BucketURL}/dns/dns.yml
      TimeoutInMinutes: '60'
      Parameters:
        OwnerNamen: !Ref OwnerNamen
        ProyectName: !Ref ProyectName
        Environment: !Ref Environment
        Ec2Ip: !GetAtt EC2.Outputs.Ec2PublicId