AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the dns conection in host trambo
Parameters:
  OwnerNamen:
    Type: String
    Default: hboiton

  ProyectName:
    Type: String
    Default: hboiton-stack
  
  Environment:
    Type: String
    Default: dev-hboiton
    Description: Environment name to append to resources names and tags
  
  HostedZoneId:
    Type: String
    Default: Z2LZ45JUYPDLLV
    Description: Hosted zone id

  HostedZoneName:
    Type: String
    Default: training.trambo.cloud
    Description: Hosted Zone name
  
  RecordName:
    Type: String
    Default: hboiton
    Description: Record name

  Ec2Ip:
    Type: String
    Description: Public Ip of Ec2 Instance

Resources: 
  DNSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: DNS name for my instance.
      Name: !Join ['', [!Ref 'RecordName', ., !Ref 'HostedZoneName', .]]
      Type: A
      TTL: '300'
      ResourceRecords:
      - !Ref Ec2Ip