AWSTemplateFormatVersion: '2010-09-09'
Description: Creates THE RDS
Parameters:
  OwnerNamen:
    Type: String
    Default: hboiton

  ProyectName:
    Type: String
    Default: hboiton-stack
  
  Environment:
    Type: String
    Default: dev-hboiton
    Description: Environment name to append to resources names and tags

  VpcId:
    Type: String
    Description: VPC Identifier

  PrivateSubnet1:
    Type: String
    Description: Subnet name
  
  PrivateSubnet2:
    Type: String
    Description: Subnet name

  DBUser:
    Type: String
    Default: mysqladmin
    Description: Name of Mysql admin user

  DBPassword:
    Type: String
    Default : F5T9!aopw!5/*7
    Description: password of mysql admin 

  DBStorage:
    Type: String
    Default: '50'
    Description: Allocated storage for db

  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    Description: DB instance class

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: My db subnet group
      DBSubnetGroupName: !Sub ${Environment}-mysubnetgroup
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${Environment}-sg-ec2
      GroupDescription: Allow HTTP and SSL connections
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-sg-ec2

  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      EC2VpcId: !Ref VpcId
      GroupDescription: EC2 access security
      DBSecurityGroupIngress:
        EC2SecurityGroupId: !Ref EC2SecurityGroup
       
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${Environment}-mysql-id
      DBName: mybd1
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBStorage
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBSecurityGroups:
      - Ref: DBSecurityGroup

Outputs:

  DbId:
    Value: !Ref Database

  SecurityGroupDB:
    Value: !Ref DBSecurityGroup

  Endpoint:
    Value: !GetAtt Database.Endpoint.Address

  EC2SecurityGroup:
    Value: !Ref EC2SecurityGroup 