AWSTemplateFormatVersion: '2010-09-09'
Description: Creates THE INSTANCE EC2
Parameters:
  OwnerNamen:
    Type: String
    Default: hboiton

  ProyectName:
    Type: String
    Default: hboiton-stack
  
  Environment:
    Type: String
    Default: dev-hboiton
    Description: Environment name to append to resources names and tags
  
  DBName:
    Type: String
    Default: mywordpress
    Description: Name of Mysql database
  
  DBUser:
    Type: String
    Default: mysqladmin
    Description: Name of Mysql admin user

  DBPassword:
    Type: String
    Default : F5T9!aopw!5/*7
    Description: password of mysql admin 

  DBAddress:
    Type: String
    Description: Database endpoint

  VpcId:
    Type: String
    Description: VPC Identifier

  SubnetID:
    Type: String
    Description: Subnet name

  SecurityGroupServer:
    Type: String
    Description: Allowed security group to reach RDS
 
  ImageId:
    Type: String
    Default: ami-0c94855ba95c71c99
    Description: AMI of the image to deploy

Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          files:
            /wp-config.php:
              content: !Join 
                - ''
                - - |
                    <?php
                  - 'define(''DB_NAME'',          '''
                  - !Ref DBName
                  - |
                    ');
                  - 'define(''DB_USER'',          '''
                  - !Ref DBUser
                  - |
                    ');
                  - 'define(''DB_PASSWORD'',      '''
                  - !Ref DBPassword
                  - |
                    ');
                  - 'define(''DB_HOST'',          '''
                  - !Ref DBAddress
                  - |
                    ');
                  - |
                    define('DB_CHARSET',       'utf8');
                  - |
                    define('DB_COLLATE',       '');
                  - |
                    $table_prefix = 'wp_';
                  - |
                    require_once( ABSPATH . 'wp-settings.php' );
              mode: '000644'
              owner: root
              group: root
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      NetworkInterfaces:
      - AssociatePublicIpAddress: True
        DeleteOnTermination: True
        DeviceIndex: 0
        GroupSet: 
          - !Ref SecurityGroupServer
        SubnetId: !Ref SubnetID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd php php-mysql -y
          cd /var/www/html
          wget https://wordpress.org/wordpress-5.1.1.tar.gz
          tar -xzf wordpress-5.1.1.tar.gz
          cp -r wordpress/* /var/www/html/
          cp -r wp-config.php /var/www/html/wordpress/wp-config.php
          rm -rf wordpress
          rm -rf wordpress-5.1.1.tar.gz
          chmod -R 755 wp-content
          chown -R apache:apache wp-content
          wget https://s3.amazonaws.com/bucketforwordpresslab-donotdelete/htaccess.txt
          mv htaccess.txt .htaccess
          chkconfig httpd on
          service httpd start
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ec2-wordpress

Outputs:

  Ec2Id:
    Value: !Ref EC2Instance

  Ec2PublicId:
    Value: !GetAtt EC2Instance.PublicIp  